/**
 * Minimal TSV reader shared by the loaders.
 *
 * The data files are generated by `front/data_source/build.sh`, so the format
 * is under our control and a full CSV parser would be overkill. What is worth
 * centralising is the handling every caller was getting slightly differently:
 * CRLF line endings, a trailing newline, and blank lines in the middle of a
 * file. Splitting on `'\n'` alone leaves a `\r` glued to the last field, which
 * for the track table means `JSON.parse` on the final column fails and the row
 * is dropped.
 */
export function tsvRows(text: string): string[][] {
  return text
    .split(/\r?\n/)
    .filter((line) => line.trim() !== '')
    .map((line) => line.split('\t'));
}
